[versions]
sentry-android = "7.15.0"
matomo = "4.1.4"

[libraries]
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android" }
matomo = { module = "com.github.matomo-org:matomo-sdk-android", version.ref = "matomo" }
